Repository Nexters/gotchai-server, pull requests merged in 2025-07, with the labels that each got.

#12 테스트 환경을 구성한다.
  .gitignore
  api/build.gradle.kts
  api/src/testFixtures/kotlin/com/gotchai/api/common/ControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/CommonDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/fixture/CommonFixture.kt
  api/src/testFixtures/kotlin/com/gotchai/api/util/RestDocsUtil.kt
  build.gradle.kts
  common/build.gradle.kts
  common/src/testFixtures/kotlin/com/gotchai/common/config/ProjectConfig.kt
  gradle/libs.versions.toml
Labels: chore

#28 뱃지 조회 API 구현
  api/build.gradle.kts
  api/src/main/kotlin/com/gotchai/api/presentation/v1/badge/BadgeController.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/badge/dto/response/BadgeResponse.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/badge/dto/response/GetMyBadgeResponse.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/badge/BadgeControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/common/ControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/BadgeDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/CommonDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/util/RestDocsUtil.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/adapter/in/BadgeCommandService.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/adapter/in/BadgeQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/dto/result/GetMyBadgeResult.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/entity/Badge.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/entity/UserBadge.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/exception/BadgeNotFoundException.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/in/BadgeCommandUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/in/BadgeQueryUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/out/BadgeCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/out/BadgeQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/out/UserBadgeQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/global/exception/ServerException.kt
  domain/src/test/kotlin/com/gotchai/domain/badge/adapter/in/BadgeQueryServiceTest.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/BadgeFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/adapter/out/BadgeCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/adapter/out/BadgeQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/adapter/out/UserBadgeQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/entity/BadgeEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/entity/UserBadgeEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/repository/BadgeJpaRepository.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/repository/UserBadgeJpaRepository.kt
Labels: refactor, feature

#30 docker compose를 구성한다.
  docker/docker-compose.yml
  domain/src/main/kotlin/com/gotchai/domain/badge/entity/Rank.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/UserFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/entity/BadgeEntity.kt
Labels: chore

#34 GitHub Actions에서 환경변수를 주입하도록 한다.
  .github/workflows/deploy.yml
  docker/docker-compose.yml
Labels: chore

#35 테스트(Exam) 도메인을 정의한다.
  api/src/main/kotlin/com/gotchai/api/global/jwt/TokenCommandProcessor.kt
  domain/src/main/kotlin/com/gotchai/domain/auth/entity/AuthenticationHistory.kt
  domain/src/main/kotlin/com/gotchai/domain/auth/port/out/AuthenticationHistoryCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/auth/port/out/AuthenticationHistoryQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/entity/Exam.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/in/ExamCommandUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/in/ExamQueryUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamQueryPort.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/BadgeFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/auth/adapter/in/AuthenticationHistoryCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/auth/adapter/in/AuthenticationHistoryQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/auth/entity/AuthenticationHistoryEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/entity/ExamEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/repository/ExamJpaRepository.kt
Labels: feature

#49 테스트 오류를 해결한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/badge/BadgeController.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/badge/response/GetMyBadgeListResponse.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/badge/BadgeControllerTest.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/exam/ExamControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/AuthDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/BadgeDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/CommonDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/ExamDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/UserDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/util/RestDocsUtil.kt
  common/logging/src/main/resources/application-logging.yml
Labels: fix

#54 CI / CD 워크플로우 오류를 해결한다.
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/test.md
  .github/workflows/deploy.yml
  docker/docker-compose.yml
Labels: fix

#57 배포 관련 오류들을 해결한다.
  .github/workflows/deploy.yml
  api/src/main/kotlin/com/gotchai/api/global/exception/GlobalExceptionHandler.kt
  docker/docker-compose.yml
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/entity/QuizEntity.kt
Labels: fix
