Repository Nexters/gotchai-server, pull requests merged in 2025-08, with the labels that each got.

#62 내가 푼 테스트 조회 API를 구현한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/exam/ExamController.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/exam/ExamControllerTest.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/adapter/in/ExamQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/entity/ExamResult.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/in/ExamQueryUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamResultQueryPort.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/ExamFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamResultQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/entity/ExamResultEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/repository/ExamJpaRepository.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/repository/ExamResultJpaRepository.kt
Labels: feature

#63 퀴즈 단건을 조회한다.
  api/build.gradle.kts
  api/src/main/kotlin/com/gotchai/api/presentation/v1/quiz/QuizController.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/quiz/response/QuizDetailResponse.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/quiz/response/QuizPickListResponse.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/quiz/response/QuizPickResponse.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/quiz/QuizControllerTest.kt
  api/src/test/resources/tags.yml
  api/src/testFixtures/kotlin/com/gotchai/api/docs/QuizDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/util/RestDocsUtil.kt
  build.gradle.kts
  domain/src/main/kotlin/com/gotchai/domain/quiz/adapter/in/QuizQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/dto/result/GetQuizResult.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/port/in/QuizQueryUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/port/out/QuizPickQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/port/out/QuizQueryPort.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/QuizFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizPickCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizPickQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/entity/QuizPickEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/repository/QuizPickJpaRepository.kt
Labels: feature

#66 애플 Public Key 통신 후 응답 구조 수정한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/exam/ExamController.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/exam/ExamControllerTest.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/ExamFixture.kt
  infrastructure/oauth/src/main/kotlin/com/gotchai/infrastructure/oauth/client/AppleClient.kt
  infrastructure/oauth/src/main/kotlin/com/gotchai/infrastructure/oauth/dto/ApplePublicKeyResponse.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamResultQueryAdapter.kt
Labels: fix

#73 테스트 결과를 제출한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/exam/ExamController.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/exam/response/SubmitExamResponse.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/exam/ExamControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/SubmitExamDocs.kt
  docker/docker-compose.yml
  domain/src/main/kotlin/com/gotchai/domain/badge/adapter/in/BadgeCommandService.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/adapter/in/BadgeQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/entity/Tier.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/exception/InvalidBadgeTierException.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/in/BadgeCommandUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/in/BadgeQueryUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/out/BadgeQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/badge/port/out/UserBadgeCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/adapter/in/ExamCommandService.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/adapter/in/ExamQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/dto/result/ExamSubmitResult.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/entity/ExamResult.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/exception/ExamHistoryNotFoundException.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/in/ExamCommandUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/in/ExamQueryUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamHistoryCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamHistoryQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamResultCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/adapter/in/QuizCommandService.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/adapter/in/QuizQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/entity/QuizHistory.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/exception/QuizNotFoundException.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/port/out/QuizQueryPort.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/ExamFixture.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/ExamSubmitResultFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/adapter/out/BadgeQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/adapter/out/UserBadgeCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/badge/repository/BadgeJpaRepository.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamResultCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamResultQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/entity/ExamResultEntity.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizQueryAdapter.kt
  storage/redis/src/main/kotlin/com/gotchai/storage/redis/exam/adapter/out/ExamHistoryCommandAdapter.kt
  storage/redis/src/main/kotlin/com/gotchai/storage/redis/exam/adapter/out/ExamHistoryQueryAdapter.kt
Labels: feature

#94 Multipart 전용 테스트 환경을 구성한다.
  api/src/main/kotlin/com/gotchai/api/global/config/SecurityConfig.kt
  api/src/main/kotlin/com/gotchai/api/global/security/CustomAuthenticationEntryPoint.kt
  api/src/main/kotlin/com/gotchai/api/global/util/WebUtil.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/badge/BadgeControllerTest.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/exam/ExamControllerTest.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/quiz/QuizControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/common/ControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/AdminDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/AuthDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/BadgeDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/CommonDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/ExamDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/QuizDocs.kt
  api/src/testFixtures/kotlin/com/gotchai/api/fixture/AdminFixture.kt
  api/src/testFixtures/kotlin/com/gotchai/api/fixture/ExamFixture.kt
  api/src/testFixtures/kotlin/com/gotchai/api/util/RestDocsUtil.kt
  api/src/testFixtures/kotlin/com/gotchai/api/util/WebTestClientUtil.kt
  build.gradle.kts
  domain/src/main/kotlin/com/gotchai/domain/badge/adapter/in/BadgeQueryService.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/ExamFixture.kt
Labels: chore

#105 상위 랭크에 대한 API를 구현한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/user/UserController.kt
  api/src/main/kotlin/com/gotchai/api/presentation/v1/user/response/UserRankingResponse.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/user/UserControllerTest.kt
  api/src/testFixtures/kotlin/com/gotchai/api/docs/UserDocs.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamHistoryQueryPort.kt
  domain/src/main/kotlin/com/gotchai/domain/user/adapter/in/UserQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/user/dto/result/GetUserRankingResult.kt
  domain/src/main/kotlin/com/gotchai/domain/user/port/in/UserQueryUseCase.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/UserFixture.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamHistoryQueryAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/repository/ExamHistoryJpaRepository.kt
Labels: feature

#111 유저 랭킹 조회 API 엔드포인트를 수정한다.
  api/src/test/kotlin/com/gotchai/api/presentation/v1/user/UserControllerTest.kt
Labels: fix

#113 워크플로 빌드 시 Gradle 캐시를 도입한다.
  .github/workflows/deploy.yml
Labels: chore

#115 랭킹(rating) 올림 처리로 수정한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/user/response/UserRankingResponse.kt
  domain/src/main/kotlin/com/gotchai/domain/user/adapter/in/UserQueryService.kt
  domain/src/main/kotlin/com/gotchai/domain/user/dto/result/GetUserRankingResult.kt
  domain/src/testFixtures/kotlin/com/gotchai/domain/fixture/UserFixture.kt
Labels: feature

#104 테스트 기록 초기화 API를 구현한다.
  api/src/main/kotlin/com/gotchai/api/presentation/v1/admin/AdminController.kt
  api/src/test/kotlin/com/gotchai/api/presentation/v1/admin/AdminControllerTest.kt
  domain/src/main/kotlin/com/gotchai/domain/admin/adapter/in/AdminCommandService.kt
  domain/src/main/kotlin/com/gotchai/domain/admin/port/in/AdminCommandUseCase.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/adapter/in/ExamCommandService.kt
  domain/src/main/kotlin/com/gotchai/domain/exam/port/out/ExamHistoryCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/port/out/QuizHistoryCommandPort.kt
  domain/src/main/kotlin/com/gotchai/domain/quiz/port/out/QuizHistoryQueryPort.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/adapter/out/ExamHistoryCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/exam/repository/ExamHistoryJpaRepository.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizHistoryCommandAdapter.kt
  storage/rdb/src/main/kotlin/com/gotchai/storage/rdb/quiz/adapter/out/QuizHistoryQueryAdapter.kt
Labels: feature
